#!/bin/bash -ve

if [ ! -d "build" ]; then
    mkdir build;
fi

sudo apt -y install devscripts git git-buildpackage
pushd build

for i in `cat ../packages`; do
    sudo dpkg -i *.deb || true
    sudo apt --fix-broken install
    if [ ! -f "$i.build" ]; then
        if [ ! -d "$i" ]; then
            git clone git@github.com:eduvpn-debian/$i
        fi
        pushd $i
        git checkout debian
        sudo mk-build-deps -i || true
	sudo apt --fix-broken install
	rm -f *-build-deps_*_all.deb 
        gbp buildpackage --git-debian-branch=debian --git-upstream-tag='%(version)s' --git-ignore-new
        popd
        touch $i.build
    fi
done
