#!/bin/bash -ve

sudo apt install apt-transport-https
curl -L https://repo.eduvpn.org/debian/eduvpn.key  | sudo apt-key add -
echo "deb https://repo.eduvpn.org/debian/ stretch main" sudo tee /etc/apt/sources.list.d/eduvpn.list
sudo apt update
