#!/bin/bash -ve

if [ ! -d "build" ]; then
    mkdir build;
fi

sudo apt -y install devscripts git git-buildpackage equivs
pushd build

for i in `cat ../packages`; do
    if [ ! -f "$i.build" ]; then
        if [ ! -d "$i" ]; then
            git clone git@github.com:eduvpn-debian/$i
        fi
        sudo apt --fix-broken install
        pushd $i
        dh_clean
        git pull
        sudo mk-build-deps -i || true
        sudo apt --fix-broken install
        rm -f *-build-deps_*_all.deb 
        dh_clean
        gbp buildpackage --git-ignore-new
        popd
        touch $i.build
    fi
done
