#!/bin/bash -ve


echo "* run this from a debian source folder"

dh_clean
git pull
git checkout upstream
git checkout master
git clean -f -d
gbp import-orig --uscan
gbp dch -D stable
git commit debian/changelog -m "new upstream release"
gbp buildpackage --git-tag
git push --all
git push --tags
